# Generated by Django 6.0.7 on 2026-08-02 08:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('filename', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('page_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('QUEUED', '대기'), ('RENDERING', '쪽 세는 중'), ('OCR', '글자 읽는 중'), ('DONE', '끝'), ('FAILED', '실패'), ('CANCELLED', '멈춤')], db_index=True, default='QUEUED', max_length=12)),
                ('last_error', models.TextField(blank=True, default='')),
                ('endpoint', models.CharField(blank=True, default='', max_length=255)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('split_pages', models.BooleanField(default=False)),
                ('worker_id', models.CharField(blank=True, default='', max_length=64)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_no', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('DONE', '끝'), ('FAILED', '실패')], db_index=True, default='PENDING', max_length=8)),
                ('text', models.TextField(blank=True, default='')),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ocr.job')),
            ],
            options={
                'ordering': ['page_no'],
                'indexes': [models.Index(fields=['job', 'status'], name='ocr_page_job_id_f30017_idx')],
                'unique_together': {('job', 'page_no')},
            },
        ),
    ]
