# Generated by Django 6.0.7 on 2026-08-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='boxes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
