"""
Django settings for exapdfsrv project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

# 설정은 전부 .env 에서 읽는다. 소스에 하드코딩하지 않는다 (CLAUDE.md §2 규칙 3)
load_dotenv(BASE_DIR / '.env')


def _env(key, default=''):
    return os.environ.get(key, default).strip()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 개발용 기본값이 있지만 운영에서는 .env 로 반드시 덮어쓴다
SECRET_KEY = _env('SECRET_KEY') or 'dev-only-do-not-use-in-production'

DEBUG = _env('DEBUG', '1') == '1'

ALLOWED_HOSTS = [h.strip() for h in _env('ALLOWED_HOSTS', '*').split(',') if h.strip()]

# ── OCR 설정 ─────────────────────────────────────────────
# 앱이 이 서버를 부를 때 쓰는 토큰. **비어 있으면 모든 요청을 거부한다** —
# 설정을 빠뜨렸을 때 열린 채로 도는 것이 가장 나쁘다
OCR_API_TOKEN = _env('API_TOKEN')

# 글자를 읽어 줄 Ollama. 이 서버와 같은 기기가 아니어도 된다
OCR_ENDPOINT = _env('OCR_ENDPOINT')
OCR_MODEL = _env('OCR_MODEL', 'qwen2.5vl:7b')

OCR_UPLOAD_DIR = Path(_env('UPLOAD_DIR') or (BASE_DIR / 'uploads'))

# 스캔본은 크다. 통째로 메모리에 올리지 않고 파일로 흘린다
FILE_UPLOAD_MAX_MEMORY_SIZE = 4 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 4 * 1024 * 1024


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ocr',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'exapdfsrv.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'exapdfsrv.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
