import json, csv, re, unicodedata
from pathlib import Path

SRC = Path('/mnt/data/붙여넣은 텍스트 (1)(4).txt')
OUT = Path('/mnt/data')
base = json.loads(SRC.read_text(encoding='utf-8'))

# 기존 데이터에서 서로 다른 개념을 한 카드에 묶은 항목과 시의성 문구를 교정한다.
patch = {
    '백업 / 복원': ('복원', 'restore', '백업해 둔 데이터나 시스템을 다시 사용할 수 있는 상태로 되돌리는 작업.'),
    'MySQL / PostgreSQL': ('PostgreSQL', 'PostgreSQL', '기능이 풍부하고 표준 준수도가 높은 오픈소스 관계형 데이터베이스.'),
    '에뮬레이터 / 시뮬레이터': ('에뮬레이터', 'emulator', '다른 기기의 하드웨어와 운영체제 동작을 소프트웨어로 흉내 내는 테스트 환경.'),
    '기획자 / 디자이너': ('제품 관리자', 'Product Manager', '사용자 문제와 사업 목표를 정리하고 무엇을 어떤 순서로 만들지 결정하는 역할.'),
    '푸시 / 풀': ('푸시', 'push', '로컬 저장소의 커밋을 원격 저장소로 올리는 Git 작업.'),
    'SELECT / INSERT / UPDATE / DELETE': ('SELECT', 'SELECT', 'SQL에서 조건에 맞는 데이터를 조회하는 명령.'),
    'WHERE / ORDER BY': ('WHERE', 'WHERE', 'SQL 조회·수정·삭제 대상에 조건을 적용하는 구문.'),
    '커밋 / 롤백': ('DB 커밋', 'database commit', '트랜잭션에서 수행한 변경을 데이터베이스에 최종 확정하는 작업.'),
    '테스트 / QA': ('소프트웨어 테스트', 'software testing', '예상한 동작과 실제 동작을 비교해 결함을 찾고 품질을 확인하는 과정.'),
    '리텐션 / DAU·MAU': ('리텐션', 'retention', '처음 사용한 사람이 일정 시간이 지난 뒤 다시 돌아오는 비율.'),
    '데이터 안전 / 콘텐츠 등급': ('데이터 안전 섹션', 'Data safety section', '앱이 수집·공유·보호하는 사용자 데이터를 스토어에 공개하는 항목.'),
    '앱 서명 / 키스토어': ('앱 서명', 'app signing', '배포 파일의 제작자와 무결성을 증명하는 디지털 서명 절차.'),
    '문서 / 컬렉션': ('문서', 'document', '문서형 데이터베이스에서 한 개의 객체 데이터를 저장하는 단위.'),
    '커넥션 / 커넥션 풀': ('커넥션 풀', 'connection pool', '데이터베이스 연결을 미리 만들고 재사용해 연결 비용을 줄이는 구조.'),
    'Capacitor / Cordova': ('Capacitor', 'Capacitor', '웹 기술로 만든 앱이 카메라 같은 네이티브 기능을 사용하도록 연결하는 런타임.'),
    'REST / 엔드포인트': ('REST', 'REST', '자원을 URL로 표현하고 HTTP 메서드로 다루는 API 설계 방식.'),
    'React / React Native': ('React', 'React', '컴포넌트와 상태를 이용해 웹 사용자 인터페이스를 만드는 라이브러리.'),
    '빌드 / APK': ('APK', 'Android Package Kit', '안드로이드 기기에 직접 설치할 수 있는 앱 패키지 파일 형식.'),
    'Firestore / 실시간 DB': ('Cloud Firestore', 'Cloud Firestore', '문서와 컬렉션 구조를 사용하며 실시간 동기화를 지원하는 Firebase 데이터베이스.'),
    '셸 / 배시': ('셸', 'shell', '사용자의 명령을 해석해 운영체제 기능을 실행하는 명령 환경.'),
    '패키지 / 라이브러리': ('패키지 매니저', 'package manager', '라이브러리 설치·업데이트·버전 고정을 관리하는 도구.'),
    '스위치/토글': ('스위치', 'switch', '두 상태 가운데 하나를 즉시 켜거나 끄는 설정용 UI 컨트롤.'),
    '요청/응답': ('HTTP 응답', 'HTTP response', '서버가 요청 처리 결과와 상태 코드·데이터를 클라이언트에 돌려주는 메시지.'),
    '라우트 / 라우팅': ('라우트', 'route', '특정 URL이나 화면 이름을 실제 화면 또는 처리 함수에 연결한 규칙.'),
    '앱바 / 툴바': ('앱바', 'app bar', '화면 상단에서 제목·탐색·주요 작업을 제공하는 UI 영역.'),
    'APK / AAB': ('Android App Bundle', 'AAB', 'Google Play가 기기별 최적 APK를 생성하도록 제출하는 안드로이드 배포 형식.'),
    '빌드 넘버 / 버전': ('빌드 번호', 'build number', '스토어가 각 배포본을 구분할 때 사용하는 증가형 내부 버전 값.'),
    '앱스토어 / 플레이스토어': ('Apple App Store', 'App Store', '애플 기기용 앱을 심사·배포·판매하는 공식 앱 마켓.'),
    '키스토어 (Keystore) / 서명': ('키스토어', 'keystore', '앱 서명에 사용하는 개인 키와 인증서를 안전하게 보관하는 파일 또는 저장소.'),
    '에러 / 예외': ('예외', 'exception', '프로그램 실행 중 예상 가능한 비정상 상황을 코드로 전달하는 객체나 신호.'),
    '로그인 / 회원가입': ('회원가입', 'sign up', '새 사용자 계정과 필요한 기본 정보를 생성하는 절차.'),
    '스마트존·멍청존': ('컨텍스트 포화', 'context saturation', '대화와 자료가 지나치게 누적되어 중요한 지시를 놓치거나 응답 품질이 흔들리는 상태.'),
}
for item in base:
    if item['termKo'] in patch:
        ko,en,df = patch[item['termKo']]
        item['termKo'], item['termEn'], item['def'] = ko,en,df
    if item['termKo'] == '개발자 계정':
        item['def'] = '앱을 스토어에 등록·배포하려고 만드는 개발자용 계정. 비용과 확인 요건은 스토어 정책을 확인해야 합니다.'
        item['volatile'] = True
    if item['termKo'] == '클로즈드 테스트':
        item['def'] = '초대한 테스터만 참여하는 비공개 배포 단계. 일부 신규 Google Play 개인 계정에는 12명·14일 요건이 적용됩니다.'
        item['volatile'] = True
        item['checkedAt'] = '2026-07-22'
    if item['termKo'] == '타겟 API 레벨':
        item['def'] = '앱이 대상으로 선언한 안드로이드 API 수준. Google Play 제출 기준은 매년 바뀌므로 공식 요구사항을 확인해야 합니다.'
        item['volatile'] = True
        item['checkedAt'] = '2026-07-22'
    item.setdefault('aliases', [])
    if not item.get('termEn'):
        item['termEn'] = item['termKo']
    item.setdefault('quizEnabled', True)
    item.setdefault('reviewStatus', 'reviewed-2026-07')

# 신규 용어 500개. 한 항목에 한 개념만 담고 초보자가 실제 바이브코딩에서 마주치는 순서로 구성한다.
A=[]
def add(ko,en,df,cat,diff=2,core=False,aliases=None):
    
    if isinstance(core, list) and aliases is None:
        aliases, core = core, False
    A.append({'termKo':ko,'termEn':en,'def':df,'category':cat,'difficulty':diff,'vibeCore':core,'aliases':aliases or []})

# 1) 생성형 AI·모델
cat='생성형 AI·모델'
add('대규모 언어 모델','Large Language Model','많은 텍스트를 학습해 문장을 이해하고 생성하는 AI 모델.',cat,1,True,['LLM'])
add('생성형 AI','generative AI','글·이미지·음성·코드처럼 새로운 결과물을 만들어내는 AI.',cat,1,True)
add('멀티모달','multimodal','텍스트뿐 아니라 이미지·음성·영상 등 여러 입력 형식을 함께 다루는 능력.',cat,2,True)
add('임베딩','embedding','텍스트나 이미지의 의미를 비교할 수 있도록 숫자 벡터로 바꾼 표현.',cat,2,True)
add('벡터','vector','여러 숫자를 순서대로 묶은 값으로, AI에서는 의미와 특징을 표현하는 데 사용.',cat,2)
add('유사도','similarity','두 벡터나 데이터가 의미상 얼마나 가까운지 나타내는 값.',cat,2)
add('코사인 유사도','cosine similarity','두 벡터가 가리키는 방향의 유사성을 비교하는 대표 계산법.',cat,3)
add('어텐션','attention','입력의 여러 부분 가운데 현재 출력에 중요한 부분에 가중치를 주는 구조.',cat,3)
add('트랜스포머','Transformer','어텐션을 중심으로 문맥을 처리하는 현대 언어 모델의 대표 신경망 구조.',cat,3)
add('추론 모델','reasoning model','복잡한 문제를 여러 단계로 분석하고 계산하는 데 특화된 AI 모델.',cat,2,True)
add('베이스 모델','base model','특정 업무에 맞추기 전 일반적인 데이터로 학습된 기본 모델.',cat,3)
add('파운데이션 모델','foundation model','여러 작업에 재사용할 수 있도록 대규모 데이터로 학습한 범용 모델.',cat,3)
add('모델 체크포인트','model checkpoint','학습 중 특정 시점의 모델 가중치를 저장한 파일.',cat,3)
add('파인튜닝','fine-tuning','기존 모델을 특정 데이터와 목적에 맞게 추가 학습하는 작업.',cat,2,True)
add('지도 미세조정','supervised fine-tuning','입력과 모범 답변 쌍을 이용해 모델의 응답 방식을 추가 학습하는 방법.',cat,3,['SFT'])
add('선호도 최적화','preference optimization','여러 답변 중 사람이 선호하는 방향으로 모델 행동을 조정하는 학습 방법.',cat,4)
add('지식 증류','knowledge distillation','큰 모델의 지식과 행동을 더 작은 모델에 전달해 가볍게 만드는 기법.',cat,3)
add('양자화','quantization','모델 숫자의 정밀도를 낮춰 메모리 사용량과 실행 비용을 줄이는 기법.',cat,3)
add('컨텍스트 길이','context length','모델이 한 요청에서 참고할 수 있는 토큰의 최대 범위.',cat,2,True)
add('출력 한도','output limit','모델이 한 번의 응답에서 생성할 수 있는 최대 토큰 수.',cat,2)
add('샘플링','sampling','모델이 다음 토큰 후보의 확률을 바탕으로 실제 출력을 고르는 과정.',cat,3)
add('온도','temperature','출력의 다양성과 무작위성을 조절하는 생성 설정.',cat,2,True)
add('Top-p','top-p','누적 확률이 일정 범위가 될 때까지의 후보만 사용해 토큰을 고르는 설정.',cat,3)
add('결정적 출력','deterministic output','같은 입력과 설정에서 가능한 한 같은 결과가 나오도록 제한한 출력 방식.',cat,3)
add('스트리밍 응답','streaming response','답변이 완성될 때까지 기다리지 않고 생성되는 조각을 즉시 전달하는 방식.',cat,2,True)
add('첫 토큰 지연','time to first token','요청 후 첫 번째 출력 토큰이 도착하기까지 걸린 시간.',cat,3,aliases=['TTFT'])
add('모델 지연시간','model latency','AI 요청부터 전체 응답이 끝날 때까지 걸리는 시간.',cat,2)
add('모델 처리량','model throughput','일정 시간 동안 모델이 처리하거나 생성할 수 있는 토큰 양.',cat,3)
add('배치 추론','batch inference','여러 요청을 묶어 한꺼번에 처리해 비용과 처리 효율을 높이는 방식.',cat,3)
add('온라인 추론','online inference','사용자 요청이 들어올 때마다 즉시 모델 결과를 생성하는 방식.',cat,3)
add('모델 라우팅','model routing','요청 난이도·비용·속도에 따라 사용할 모델을 자동 선택하는 구조.',cat,3,True)
add('모델 폴백','model fallback','주 모델이 실패하거나 느릴 때 다른 모델로 자동 전환하는 처리.',cat,3)
add('오픈 웨이트 모델','open-weight model','학습된 가중치를 공개해 직접 실행하거나 조정할 수 있는 모델.',cat,3)
add('로컬 모델','local model','클라우드 API가 아니라 사용자 기기나 자체 서버에서 실행하는 AI 모델.',cat,2)
add('온디바이스 AI','on-device AI','데이터를 서버로 보내지 않고 휴대폰이나 PC 안에서 실행하는 AI.',cat,2)
add('비전 모델','vision model','이미지의 내용·문자·구조를 이해하거나 분석하는 AI 모델.',cat,2)
add('음성 인식','speech-to-text','사람의 음성을 문자 데이터로 변환하는 기술.',cat,2,['STT'])
add('음성 합성','text-to-speech','문자 내용을 자연스러운 음성으로 읽어주는 기술.',cat,2,['TTS'])
add('이미지 생성 모델','image generation model','텍스트 지시나 참조 이미지를 바탕으로 새로운 이미지를 만드는 모델.',cat,2)
add('모델 안전성','model safety','모델이 위험하거나 부적절한 결과를 줄이도록 설계·평가하는 영역.',cat,3)
add('모델 정렬','model alignment','모델 행동을 사람의 의도·가치·규칙에 맞추는 과정.',cat,4)
add('편향','bias','데이터나 모델 때문에 특정 집단·관점에 결과가 치우치는 현상.',cat,2)
add('데이터 오염','data contamination','평가 문제나 정답이 학습 데이터에 포함되어 성능이 과대평가되는 문제.',cat,4)
add('벤치마크','benchmark','모델이나 시스템 성능을 같은 조건에서 비교하는 표준 문제와 지표.',cat,2)
add('평가 데이터셋','evaluation dataset','모델 품질을 측정하려고 따로 준비한 입력과 기대 결과 모음.',cat,2)
add('정답 기준','ground truth','평가에서 비교 기준으로 사용하는 검증된 정답이나 사실.',cat,2)
add('제로샷','zero-shot','예시를 주지 않고 지시만으로 새로운 작업을 수행하게 하는 방식.',cat,2)
add('원샷','one-shot','하나의 예시를 제공해 모델이 작업 형식을 이해하게 하는 방식.',cat,2)
add('퓨샷','few-shot','몇 개의 입력·출력 예시를 제공해 모델의 응답 패턴을 유도하는 방식.',cat,2)
add('인컨텍스트 러닝','in-context learning','가중치를 다시 학습하지 않고 프롬프트 속 설명과 예시로 작업을 익히게 하는 방식.',cat,3)
add('합성 데이터','synthetic data','사람이 직접 수집하지 않고 모델이나 규칙으로 생성한 학습·테스트 데이터.',cat,3)

# 2) 프롬프트·컨텍스트·RAG
cat='프롬프트·컨텍스트·RAG'
add('시스템 지시','system instruction','모델의 역할·규칙·우선순위를 정하는 가장 상위 수준의 지시.',cat,2,True)
add('사용자 지시','user instruction','사용자가 현재 요청에서 모델에게 수행하라고 전달한 내용.',cat,1,True)
add('개발자 지시','developer instruction','앱 제작자가 모델 행동과 출력 형식을 정하려고 제공하는 지시.',cat,2)
add('프롬프트 템플릿','prompt template','반복 작업에 변수만 바꿔 재사용할 수 있게 만든 지시문 틀.',cat,2,True)
add('역할 프롬프트','role prompt','모델에게 전문가·검토자 같은 역할을 부여하는 지시 방식.',cat,2)
add('제약 조건','constraint','답변 길이·형식·금지 사항처럼 결과가 따라야 할 제한.',cat,1,True)
add('출력 형식','output format','표·JSON·코드처럼 모델이 결과를 내야 하는 구조.',cat,1,True)
add('예시 기반 지시','example-based instruction','원하는 결과 예시를 보여주어 모델이 형식과 품질을 따라가게 하는 방법.',cat,2)
add('부정 지시','negative instruction','하지 말아야 할 행동이나 포함하지 말아야 할 내용을 명시하는 지시.',cat,2)
add('프롬프트 체이닝','prompt chaining','큰 작업을 여러 개의 작은 프롬프트 단계로 연결해 처리하는 방식.',cat,2,True)
add('프롬프트 버전','prompt version','프롬프트 변경 이력을 구분하기 위해 붙이는 버전 값.',cat,2)
add('프롬프트 회귀','prompt regression','프롬프트를 고친 뒤 이전에 잘 되던 사례의 품질이 떨어지는 현상.',cat,3)
add('프롬프트 인젝션','prompt injection','외부 문서나 입력이 원래 지시를 무시하도록 모델을 속이는 공격.',cat,2,True)
add('간접 프롬프트 인젝션','indirect prompt injection','웹페이지·이메일·파일 안에 숨긴 지시로 에이전트 행동을 바꾸려는 공격.',cat,3,True)
add('탈옥','jailbreak','모델의 안전 규칙을 우회하도록 입력을 조작하는 시도.',cat,2)
add('컨텍스트 우선순위','context priority','충돌하는 여러 지시와 자료 가운데 무엇을 먼저 따라야 하는지의 순서.',cat,3)
add('컨텍스트 오염','context poisoning','잘못되거나 악의적인 정보가 컨텍스트에 들어가 이후 판단을 흐리는 문제.',cat,3)
add('컨텍스트 드리프트','context drift','대화가 길어지며 초기 목표와 규칙에서 점차 벗어나는 현상.',cat,3)
add('컨텍스트 선택','context selection','현재 작업에 필요한 파일·문서·대화만 골라 모델에 제공하는 작업.',cat,2,True)
add('컨텍스트 패킹','context packing','제한된 토큰 안에 중요한 정보를 효율적으로 정리해 넣는 과정.',cat,3)
add('컨텍스트 요약','context summarization','긴 대화나 문서를 핵심 정보만 남겨 짧게 압축하는 작업.',cat,2)
add('컨텍스트 격리','context isolation','서로 다른 사용자나 작업의 정보를 섞이지 않게 분리하는 설계.',cat,3)
add('검색 증강 생성','retrieval-augmented generation','외부 문서를 검색해 근거로 넣은 뒤 답변을 생성하는 방식.',cat,2,True,['RAG'])
add('검색기','retriever','질문과 관련된 문서 조각을 찾아 모델에 전달하는 구성 요소.',cat,3)
add('문서 분할','chunking','긴 문서를 검색하기 좋은 작은 단위로 나누는 작업.',cat,2,True)
add('청크','chunk','검색과 임베딩을 위해 잘라낸 문서의 작은 단위.',cat,2)
add('청크 크기','chunk size','한 문서 조각에 포함할 문자나 토큰의 양.',cat,3)
add('청크 겹침','chunk overlap','문맥 단절을 줄이기 위해 이웃 청크가 일부 내용을 공유하게 하는 설정.',cat,3)
add('벡터 검색','vector search','질문과 의미가 가까운 임베딩을 찾아 관련 문서를 검색하는 방식.',cat,2,True)
add('키워드 검색','keyword search','정확히 일치하거나 비슷한 단어를 기준으로 문서를 찾는 방식.',cat,2)
add('하이브리드 검색','hybrid search','키워드 검색과 벡터 검색 결과를 결합하는 방식.',cat,3)
add('시맨틱 검색','semantic search','같은 단어가 없어도 의미가 비슷한 내용을 찾는 검색 방식.',cat,2)
add('리랭킹','reranking','1차 검색 결과를 더 정교한 모델로 다시 점수화해 순서를 바꾸는 과정.',cat,3,True)
add('메타데이터 필터','metadata filter','날짜·작성자·카테고리 같은 부가 정보로 검색 범위를 제한하는 조건.',cat,2)
add('인덱싱','indexing','문서를 검색 가능한 구조나 벡터 저장소에 등록하는 과정.',cat,2)
add('지식 베이스','knowledge base','AI가 검색해 참고할 수 있도록 정리한 문서와 데이터 모음.',cat,2,True)
add('근거화','grounding','모델 답변을 제공된 문서·도구 결과·검증 가능한 사실에 묶는 방법.',cat,2,True)
add('출처 인용','citation','답변의 근거가 된 문서 위치나 링크를 표시하는 것.',cat,2)
add('검색 적중률','retrieval recall','필요한 관련 문서가 검색 결과에 포함된 비율.',cat,4)
add('검색 정밀도','retrieval precision','검색된 문서 가운데 실제로 관련 있는 문서의 비율.',cat,4)
add('쿼리 재작성','query rewriting','사용자 질문을 검색에 더 잘 맞는 표현으로 바꾸는 과정.',cat,3)
add('다중 쿼리 검색','multi-query retrieval','한 질문을 여러 검색문으로 바꿔 결과 범위를 넓히는 방식.',cat,3)
add('가상 문서 임베딩','hypothetical document embedding','질문의 가상 답변을 만든 뒤 그 임베딩으로 관련 문서를 찾는 기법.',cat,4,['HyDE'])
add('문맥 압축','contextual compression','검색된 문서에서 질문에 필요한 부분만 추려 모델에 넣는 과정.',cat,3)
add('RAG 평가','RAG evaluation','검색 관련성·근거 충실도·답변 정확성을 따로 측정하는 평가.',cat,3)
add('충실도','faithfulness','생성 답변이 제공된 근거에서 벗어나지 않는 정도.',cat,3)
add('답변 관련성','answer relevance','생성된 답변이 사용자의 실제 질문에 얼마나 직접 답하는지의 정도.',cat,3)
add('문서 최신성','document freshness','검색 자료가 현재 시점과 업무 상태를 얼마나 잘 반영하는지의 속성.',cat,2)
add('출처 신뢰도','source credibility','문서 작성 주체와 검증 수준을 바탕으로 근거를 믿을 수 있는 정도.',cat,2)
add('프롬프트 캐싱','prompt caching','반복되는 긴 입력을 재사용해 지연시간과 토큰 비용을 줄이는 기능.',cat,2,True)

# 3) 에이전트·도구·바이브코딩
cat='에이전트·바이브코딩'
add('에이전트 루프','agent loop','모델이 판단하고 도구를 호출한 뒤 결과를 다시 읽는 과정을 반복하는 구조.',cat,2,True)
add('함수 호출','function calling','모델이 정해진 스키마에 맞춰 프로그램 함수를 실행하도록 요청하는 기능.',cat,2,True)
add('구조화 출력','structured output','모델 결과를 JSON 스키마 같은 정해진 구조에 맞게 제한하는 기능.',cat,2,True)
add('JSON 스키마','JSON Schema','JSON 데이터의 필드·자료형·필수 여부를 정의하는 표준 형식.',cat,3)
add('도구 스키마','tool schema','에이전트가 사용할 도구 이름·설명·입력 필드를 정의한 구조.',cat,2)
add('도구 선택','tool selection','현재 요청을 해결하기 위해 어떤 도구를 호출할지 결정하는 과정.',cat,2)
add('도구 권한','tool permission','도구가 읽기·쓰기·실행할 수 있는 범위를 제한하는 설정.',cat,2,True)
add('승인 게이트','approval gate','파일 삭제·결제처럼 위험한 행동 전에 사람의 확인을 요구하는 단계.',cat,2,True)
add('가드레일','guardrail','입력·출력·도구 사용이 규칙을 지키는지 검사하고 위험 행동을 막는 장치.',cat,2,True)
add('트립와이어','tripwire','위험 조건이 감지되면 에이전트 실행을 즉시 중단시키는 신호.',cat,3)
add('도구 타임아웃','tool timeout','도구 실행이 정해진 시간을 넘으면 실패로 처리하는 제한.',cat,2)
add('도구 재시도','tool retry','일시적인 실패가 발생했을 때 같은 도구 실행을 다시 시도하는 처리.',cat,2)
add('지수 백오프','exponential backoff','재시도 간격을 점점 늘려 서버 부담과 연속 실패를 줄이는 방식.',cat,3)
add('멱등성','idempotency','같은 요청을 여러 번 실행해도 최종 결과가 한 번 실행한 것과 같은 성질.',cat,3)
add('핸드오프 규칙','handoff rule','어떤 조건에서 현재 에이전트가 전문 에이전트에게 일을 넘길지 정한 기준.',cat,3)
add('에이전트 오케스트레이션','agent orchestration','여러 에이전트와 도구의 역할·순서·상태를 조정하는 구조.',cat,3,True)
add('전문 에이전트','specialist agent','코드 리뷰·테스트처럼 특정 업무만 집중하도록 지시와 도구를 제한한 에이전트.',cat,2)
add('관리자 에이전트','manager agent','큰 작업을 나누고 여러 전문 에이전트 결과를 모으는 에이전트.',cat,3)
add('에이전트 도구화','agent as tool','한 에이전트를 다른 에이전트가 호출할 수 있는 도구처럼 사용하는 방식.',cat,3)
add('에이전트 추적','agent tracing','모델 호출·도구 실행·핸드오프 흐름을 시간순으로 기록해 살펴보는 기능.',cat,2,True)
add('실행 스팬','span','추적 데이터에서 하나의 모델 호출이나 도구 실행을 나타내는 구간.',cat,3)
add('실행 런','run','에이전트가 한 작업을 시작해 최종 결과를 내기까지의 전체 실행 단위.',cat,2)
add('작업 계획','task plan','에이전트가 목표를 작은 단계와 검증 순서로 나눈 실행 계획.',cat,1,True)
add('계획 모드','plan mode','코드를 바로 고치지 않고 먼저 조사와 변경 계획만 제시하는 모드.',cat,2,True)
add('실행 모드','execution mode','승인된 계획에 따라 실제 파일 수정·명령 실행을 수행하는 모드.',cat,2)
add('드라이 런','dry run','실제 변경을 적용하지 않고 어떤 동작이 일어날지 미리 확인하는 실행.',cat,2,True)
add('체크포인트','checkpoint','큰 변경 중간에 되돌아갈 수 있도록 저장한 안전 지점.',cat,2,True)
add('패치','patch','파일 전체가 아니라 변경된 일부 내용을 적용하는 수정 묶음.',cat,2)
add('디프','diff','수정 전후 파일에서 추가·삭제·변경된 줄을 보여주는 비교 결과.',cat,1,True)
add('컨텍스트 파일','context file','에이전트에게 프로젝트 규칙과 구조를 알려주려고 제공하는 문서.',cat,2)
add('저장소 지시','repository instruction','프로젝트 전체에 적용할 빌드·테스트·코딩 규칙을 적은 에이전트 지시.',cat,2,True)
add('경로별 지시','path-specific instruction','특정 폴더나 파일 종류에만 적용되는 에이전트 규칙.',cat,3)
add('CLAUDE.md','CLAUDE.md','Claude Code가 프로젝트 지침으로 읽을 수 있도록 저장소에 두는 마크다운 파일.',cat,2)
add('GEMINI.md','GEMINI.md','Gemini 계열 코딩 도구에 프로젝트 지침을 전달하는 마크다운 파일.',cat,2)
add('copilot-instructions.md','copilot-instructions.md','GitHub Copilot에 저장소 공통 규칙을 전달하는 지시 파일.',cat,2)
add('에이전트 스킬','agent skill','관련 작업에서 불러 쓰는 지시·스크립트·자료를 폴더로 묶은 재사용 단위.',cat,2,True)
add('MCP 서버','MCP server','AI 앱에 데이터·도구·프롬프트를 표준 방식으로 제공하는 프로그램.',cat,2,True)
add('MCP 클라이언트','MCP client','MCP 서버에 연결해 제공된 기능을 사용하는 AI 애플리케이션 구성 요소.',cat,3)
add('MCP 호스트','MCP host','여러 MCP 클라이언트 연결과 사용자 승인·보안을 관리하는 AI 애플리케이션.',cat,3)
add('MCP 리소스','MCP resource','MCP 서버가 읽기용 컨텍스트로 제공하는 파일·문서·데이터.',cat,3)
add('MCP 도구','MCP tool','MCP 서버가 에이전트가 실행할 수 있는 행동으로 제공하는 함수.',cat,3)
add('MCP 프롬프트','MCP prompt','MCP 서버가 재사용 가능한 작업 템플릿으로 제공하는 프롬프트.',cat,3)
add('스펙 주도 개발','spec-driven development','구현 전에 요구사항·동작·검증 기준을 문서로 확정하고 개발하는 방식.',cat,2,True)
add('PRD','Product Requirements Document','사용자 문제·목표·기능·성공 기준을 정리한 제품 요구사항 문서.',cat,2,True)
add('기술 명세','technical specification','기능 동작·데이터·예외·구현 제약을 개발 가능한 수준으로 적은 문서.',cat,1,True)
add('수용 기준','acceptance criteria','기능이 완료되었다고 판단할 수 있는 관찰 가능한 조건.',cat,1,True)
add('사용자 스토리','user story','특정 사용자가 어떤 목적 때문에 무엇을 원하는지 짧게 표현한 요구사항.',cat,2)
add('사용 사례','use case','사용자와 시스템이 목표를 달성하는 단계별 상호작용 시나리오.',cat,2)
add('경계 사례','edge case','일반적이지 않지만 실제로 발생할 수 있어 별도 처리가 필요한 상황.',cat,1,True)
add('실패 경로','failure path','오류·권한 거부·네트워크 단절처럼 정상 흐름에서 벗어난 처리 과정.',cat,2)
add('비기능 요구사항','non-functional requirement','속도·보안·접근성·안정성처럼 기능 외 품질 기준.',cat,2,True)
add('완료의 정의','definition of done','코드·테스트·문서·배포 준비까지 작업 완료에 필요한 팀 공통 조건.',cat,2)
add('작업 분해','task decomposition','큰 기능을 독립적으로 구현·검증할 수 있는 작은 작업으로 나누는 과정.',cat,1,True)
add('스파이크','technical spike','불확실한 기술 문제를 짧게 조사하거나 시험 구현해 위험을 줄이는 작업.',cat,3)
add('개념 증명','proof of concept','핵심 아이디어가 기술적으로 가능한지만 확인하는 작은 실험.',cat,2,['PoC'])
add('스캐폴딩','scaffolding','프로젝트나 기능의 기본 폴더와 파일을 자동 생성하는 작업.',cat,2)
add('보일러플레이트','boilerplate','여러 프로젝트에서 반복되는 기본 코드와 설정.',cat,2)
add('코드베이스','codebase','한 프로젝트를 이루는 전체 소스 코드와 관련 파일.',cat,1,True)
add('레거시 코드','legacy code','오래되었거나 현재 구조와 규칙에 맞지 않지만 계속 사용 중인 코드.',cat,2)
add('기술 부채','technical debt','빠른 선택 때문에 나중에 수정 비용과 복잡성이 늘어난 상태.',cat,2,True)
add('범위 확장','scope creep','합의 없이 요구사항이 계속 추가되어 일정과 복잡성이 커지는 현상.',cat,2)
add('최소 기능 제품','minimum viable product','핵심 가치를 검증할 최소 기능만 담아 빠르게 출시하는 제품.',cat,1,True,['MVP'])
add('기능 플래그','feature flag','배포 후에도 설정으로 새 기능을 켜고 끌 수 있게 하는 장치.',cat,2,True)
add('롤아웃','rollout','새 기능이나 버전을 사용자에게 단계적으로 공개하는 과정.',cat,2)
add('카나리 배포','canary release','일부 사용자에게 먼저 새 버전을 제공해 문제를 확인하는 배포 방식.',cat,3)
add('킬 스위치','kill switch','심각한 문제가 생겼을 때 기능을 즉시 비활성화하는 안전 장치.',cat,2)
add('관찰 모드','read-only mode','에이전트가 파일과 상태를 읽을 수 있지만 변경은 못 하게 제한한 모드.',cat,2)
add('최소 권한 원칙','principle of least privilege','작업에 꼭 필요한 최소한의 접근 권한만 주는 보안 원칙.',cat,2,True)

# 4) 프로그래밍 핵심
cat='프로그래밍 핵심'
add('상수','constant','실행 중 값이 바뀌지 않도록 정의한 데이터.',cat,1)
add('스코프','scope','변수나 함수 이름을 사용할 수 있는 코드 범위.',cat,2,True)
add('전역 변수','global variable','프로그램의 넓은 범위에서 접근할 수 있는 변수.',cat,2)
add('지역 변수','local variable','함수나 블록 안에서만 사용할 수 있는 변수.',cat,1)
add('널','null','값이 존재하지 않음을 나타내는 특별한 값.',cat,1,True)
add('널 안정성','null safety','값 없음 때문에 생기는 오류를 자료형과 검사로 줄이는 기능.',cat,2)
add('옵셔널','optional','값이 있을 수도 없을 수도 있음을 자료형으로 표현한 것.',cat,2)
add('열거형','enum','가능한 값의 목록을 이름 붙여 제한하는 자료형.',cat,2)
add('튜플','tuple','서로 다른 자료형의 값을 정해진 순서로 묶는 자료구조.',cat,2)
add('집합','set','중복 없는 값들을 저장하는 자료구조.',cat,2)
add('맵 자료구조','map data structure','키를 이용해 값을 빠르게 찾는 자료구조.',cat,2)
add('스택 자료구조','stack data structure','나중에 넣은 값을 먼저 꺼내는 후입선출 구조.',cat,2,['LIFO'])
add('큐 자료구조','queue data structure','먼저 넣은 값을 먼저 꺼내는 선입선출 구조.',cat,2,['FIFO'])
add('연결 리스트','linked list','각 요소가 다음 요소의 위치를 가리키도록 연결한 자료구조.',cat,3)
add('트리','tree data structure','부모와 자식의 계층 관계로 데이터를 표현하는 구조.',cat,2)
add('그래프 자료구조','graph data structure','노드와 연결 관계로 복잡한 네트워크를 표현하는 구조.',cat,3)
add('해시','hash','입력 데이터를 고정 길이 값으로 변환하는 계산 결과.',cat,2)
add('해시 테이블','hash table','해시를 이용해 키에 대응하는 값을 빠르게 찾는 자료구조.',cat,3)
add('클래스','class','데이터와 동작을 가진 객체를 만들기 위한 설계도.',cat,2)
add('인스턴스','instance','클래스를 바탕으로 실제 메모리에 만들어진 객체.',cat,2)
add('메서드','method','클래스나 객체에 속해 동작을 수행하는 함수.',cat,1)
add('속성','property','객체가 가지고 있는 값이나 상태.',cat,1)
add('생성자','constructor','객체가 만들어질 때 초기 상태를 설정하는 특별한 함수.',cat,2)
add('인터페이스','interface','구현해야 할 메서드와 형태를 약속하는 계약.',cat,2,True)
add('추상 클래스','abstract class','일부 공통 구현과 반드시 구현할 동작을 함께 정의하는 부모 클래스.',cat,3)
add('상속','inheritance','기존 클래스의 속성과 동작을 새 클래스가 이어받는 방식.',cat,2)
add('합성','composition','작은 객체들을 포함하고 조합해 더 큰 기능을 만드는 설계 방식.',cat,3)
add('다형성','polymorphism','같은 인터페이스를 여러 객체가 각자 다른 방식으로 구현하는 성질.',cat,3)
add('캡슐화','encapsulation','내부 상태를 숨기고 정해진 방법으로만 접근하게 하는 원칙.',cat,3)
add('의존성 주입','dependency injection','필요한 객체를 내부에서 만들지 않고 외부에서 전달받는 설계 방식.',cat,3,True)
add('제네릭','generic','자료형을 나중에 지정할 수 있게 코드를 일반화하는 기능.',cat,3)
add('콜백','callback','다른 함수에 전달되어 특정 시점에 호출되는 함수.',cat,2)
add('클로저','closure','자신이 만들어진 바깥 스코프의 변수를 기억하는 함수.',cat,3)
add('고차 함수','higher-order function','함수를 인자로 받거나 함수 자체를 반환하는 함수.',cat,3)
add('람다','lambda','이름 없이 짧게 작성하는 함수 표현식.',cat,2)
add('재귀','recursion','함수가 문제를 줄여가며 자기 자신을 다시 호출하는 방식.',cat,3)
add('기저 조건','base case','재귀 호출이 멈추도록 정한 종료 조건.',cat,3)
add('불변성','immutability','만든 뒤 값을 직접 바꾸지 않고 새 값을 만드는 성질.',cat,2)
add('순수 함수','pure function','같은 입력에는 같은 출력이며 외부 상태를 바꾸지 않는 함수.',cat,3)
add('부작용','side effect','함수가 반환값 외에 파일·화면·외부 상태를 바꾸는 동작.',cat,2)
add('동기 처리','synchronous processing','한 작업이 끝날 때까지 기다린 뒤 다음 작업을 수행하는 방식.',cat,2)
add('비동기 처리','asynchronous processing','긴 작업을 기다리는 동안 다른 작업을 진행할 수 있는 방식.',cat,2,True)
add('프로미스','Promise','미래에 완료되거나 실패할 비동기 작업의 결과를 나타내는 객체.',cat,2)
add('async/await','async/await','비동기 코드를 순차 코드처럼 읽기 쉽게 작성하는 문법.',cat,2,True)
add('이벤트 루프','event loop','대기 중인 이벤트와 비동기 작업을 순서대로 처리하는 실행 구조.',cat,3)
add('스레드','thread','한 프로세스 안에서 명령을 실행하는 작업 흐름.',cat,2)
add('프로세스','process','운영체제에서 독립된 메모리와 자원을 가진 실행 중인 프로그램.',cat,2)
add('동시성','concurrency','여러 작업이 겹치는 시간 동안 진행되도록 관리하는 성질.',cat,3)
add('병렬성','parallelism','여러 작업을 실제로 같은 시간에 동시에 실행하는 성질.',cat,3)
add('경쟁 상태','race condition','여러 작업의 실행 순서에 따라 결과가 달라지는 오류.',cat,3)
add('교착 상태','deadlock','여러 작업이 서로의 자원을 기다리며 영원히 멈춘 상태.',cat,4)
add('메모리 누수','memory leak','더 이상 필요 없는 메모리가 해제되지 않아 사용량이 계속 늘어나는 문제.',cat,3)
add('가비지 컬렉션','garbage collection','사용하지 않는 객체의 메모리를 자동으로 회수하는 기능.',cat,3)
add('스택 트레이스','stack trace','오류가 발생하기까지 호출된 함수 순서를 보여주는 기록.',cat,2,True)
add('런타임 오류','runtime error','문법 검사는 통과했지만 프로그램 실행 중 발생하는 오류.',cat,1)
add('논리 오류','logic error','프로그램은 실행되지만 계산이나 조건이 잘못되어 틀린 결과가 나오는 오류.',cat,1)
add('타입 검사','type checking','값과 연산이 선언된 자료형 규칙에 맞는지 확인하는 과정.',cat,2)
add('정적 타입','static typing','실행 전에 변수와 표현식의 자료형을 검사하는 방식.',cat,2)
add('동적 타입','dynamic typing','실행 중 실제 값에 따라 자료형이 정해지는 방식.',cat,2)
add('타입 추론','type inference','컴파일러가 코드의 값과 사용법을 보고 자료형을 자동 판단하는 기능.',cat,3)
add('직렬화','serialization','객체를 JSON이나 바이트처럼 저장·전송 가능한 형태로 바꾸는 과정.',cat,2)
add('역직렬화','deserialization','저장·전송된 데이터를 프로그램 객체로 다시 만드는 과정.',cat,2)
add('인코딩','encoding','문자나 데이터를 정해진 규칙의 바이트 표현으로 바꾸는 과정.',cat,2)
add('UTF-8','UTF-8','한글을 포함한 유니코드 문자를 바이트로 표현하는 대표 인코딩.',cat,2)
add('정규 표현식','regular expression','문자열의 패턴을 검색·검증·치환하는 표현 문법.',cat,2,['regex'])
add('파서','parser','텍스트나 코드를 문법 구조에 맞게 분석하는 프로그램.',cat,3)
add('추상 구문 트리','abstract syntax tree','소스 코드의 문법 구조를 트리 형태로 표현한 데이터.',cat,4,['AST'])

# 5) 웹·프론트엔드
cat='웹·프론트엔드'
add('DOM','Document Object Model','HTML 문서를 자바스크립트가 읽고 수정할 수 있는 객체 트리로 표현한 것.',cat,2,True)
add('가상 DOM','Virtual DOM','실제 DOM 변경을 줄이기 위해 메모리에서 UI 차이를 계산하는 표현.',cat,3)
add('CSS 선택자','CSS selector','스타일을 적용할 HTML 요소를 찾는 패턴.',cat,1)
add('박스 모델','CSS box model','요소를 콘텐츠·패딩·테두리·마진 영역으로 계산하는 CSS 규칙.',cat,2)
add('플렉스박스','Flexbox','한 방향의 요소 정렬과 간격 배치에 사용하는 CSS 레이아웃.',cat,2,True)
add('CSS 그리드','CSS Grid','행과 열을 함께 사용해 2차원 화면 배치를 만드는 CSS 레이아웃.',cat,2,True)
add('미디어 쿼리','media query','화면 크기나 기기 특성에 따라 다른 CSS를 적용하는 조건.',cat,2)
add('브레이크포인트','breakpoint','레이아웃 구성이 바뀌는 화면 너비 기준점.',cat,2)
add('뷰포트','viewport','브라우저에서 현재 페이지가 보이는 화면 영역.',cat,2)
add('시맨틱 HTML','semantic HTML','내용의 의미에 맞는 header·nav·main 같은 태그를 사용하는 작성 방식.',cat,2,True)
add('웹 접근성','web accessibility','장애 여부와 사용 환경에 관계없이 웹을 이용할 수 있게 설계하는 원칙.',cat,2,True)
add('ARIA','Accessible Rich Internet Applications','보조 기술에 UI의 역할·상태·관계를 알려주는 웹 접근성 속성.',cat,3)
add('반응형 이미지','responsive image','화면 크기와 해상도에 맞는 이미지 파일을 선택해 보여주는 방식.',cat,3)
add('CSS 변수','CSS custom property','색상·간격 같은 값을 이름으로 선언해 여러 스타일에서 재사용하는 기능.',cat,2)
add('디자인 토큰','design token','색상·크기·간격 같은 디자인 값을 이름과 데이터로 관리하는 단위.',cat,2,True)
add('CSS 애니메이션','CSS animation','키프레임을 이용해 요소의 스타일 변화를 시간에 따라 재생하는 기능.',cat,2)
add('CSS 트랜지션','CSS transition','상태가 바뀔 때 두 스타일 사이를 부드럽게 보간하는 기능.',cat,2)
add('자바스크립트 모듈','JavaScript module','코드를 파일 단위로 내보내고 가져와 재사용하는 구조.',cat,2)
add('ESM','ECMAScript Module','import와 export 문법을 사용하는 표준 자바스크립트 모듈 형식.',cat,2)
add('CommonJS','CommonJS','require와 module.exports를 사용하는 Node.js 전통 모듈 형식.',cat,3)
add('번들러','bundler','여러 자바스크립트·CSS·에셋 파일을 배포용 파일로 묶는 도구.',cat,2)
add('트랜스파일러','transpiler','최신 문법 코드를 다른 버전이나 언어의 코드로 변환하는 도구.',cat,3)
add('Babel','Babel','최신 자바스크립트 문법을 구형 환경에서도 실행 가능한 코드로 변환하는 도구.',cat,3)
add('Vite','Vite','빠른 개발 서버와 최적화된 빌드를 제공하는 프론트엔드 개발 도구.',cat,2)
add('Webpack','Webpack','자바스크립트와 에셋의 의존성을 분석해 번들로 만드는 도구.',cat,3)
add('미니파이','minification','공백과 긴 이름을 줄여 배포 파일 크기를 작게 만드는 처리.',cat,2)
add('트리 셰이킹','tree shaking','실제로 사용하지 않는 모듈 코드를 빌드 결과에서 제거하는 최적화.',cat,3)
add('코드 스플리팅','code splitting','앱 코드를 여러 묶음으로 나눠 필요한 시점에만 불러오는 최적화.',cat,3)
add('지연 로딩','lazy loading','화면에 필요해질 때 이미지나 코드를 늦게 불러오는 방식.',cat,2,True)
add('프리로딩','preloading','곧 필요할 자원을 미리 불러와 다음 동작을 빠르게 하는 방식.',cat,3)
add('클라이언트 사이드 렌더링','client-side rendering','브라우저가 자바스크립트로 화면 HTML을 만드는 렌더링 방식.',cat,2,['CSR'])
add('서버 사이드 렌더링','server-side rendering','서버가 완성한 HTML을 먼저 보내 초기 화면을 빠르게 보여주는 방식.',cat,2,True,['SSR'])
add('정적 사이트 생성','static site generation','빌드 시점에 페이지 HTML을 미리 만들어 배포하는 방식.',cat,3,['SSG'])
add('하이드레이션','hydration','서버에서 받은 HTML에 자바스크립트 동작과 상태를 연결하는 과정.',cat,3)
add('부분 하이드레이션','partial hydration','상호작용이 필요한 일부 영역에만 자바스크립트를 연결하는 최적화.',cat,4)
add('단일 페이지 앱','single-page application','페이지 전체 새로고침 없이 자바스크립트로 화면을 전환하는 웹앱.',cat,2,['SPA'])
add('다중 페이지 앱','multi-page application','URL 이동마다 서버에서 새 HTML 페이지를 받아오는 웹 구조.',cat,2,['MPA'])
add('Next.js','Next.js','React 기반으로 라우팅·서버 렌더링·빌드 기능을 제공하는 웹 프레임워크.',cat,2)
add('Vue','Vue.js','컴포넌트와 반응형 상태로 웹 UI를 만드는 자바스크립트 프레임워크.',cat,2)
add('Svelte','Svelte','컴파일 단계에서 효율적인 자바스크립트로 변환되는 UI 프레임워크.',cat,3)
add('상태 저장소','state store','여러 컴포넌트가 함께 쓰는 상태를 중앙에서 관리하는 구조.',cat,2)
add('단방향 데이터 흐름','unidirectional data flow','상태가 한 방향으로 전달되고 이벤트로만 변경되는 UI 설계.',cat,3)
add('폼 검증','form validation','입력값의 필수 여부·형식·범위를 검사하는 처리.',cat,1,True)
add('제어 컴포넌트','controlled component','입력값을 프레임워크 상태가 직접 관리하는 컴포넌트.',cat,3)
add('웹 컴포넌트','Web Components','브라우저 표준으로 캡슐화된 재사용 UI 요소를 만드는 기술 모음.',cat,3)
add('서비스 워커','service worker','브라우저 뒤에서 캐시·오프라인·푸시 처리를 수행하는 스크립트.',cat,3)
add('웹 매니페스트','web app manifest','PWA의 이름·아이콘·시작 화면·표시 방식을 정의하는 JSON 파일.',cat,3)
add('오프라인 우선','offline-first','네트워크가 없어도 핵심 기능이 동작하도록 로컬 데이터를 먼저 사용하는 설계.',cat,2,True)
add('CORS','Cross-Origin Resource Sharing','다른 출처의 웹페이지가 서버 자원에 접근할 수 있는 조건을 정하는 정책.',cat,2,True)
add('동일 출처 정책','same-origin policy','출처가 다른 웹 자원 접근을 기본적으로 제한하는 브라우저 보안 규칙.',cat,3)
add('쿠키','cookie','브라우저가 사이트별로 저장해 요청에 함께 보내는 작은 데이터.',cat,2)
add('세션 스토리지','sessionStorage','브라우저 탭을 닫을 때까지 유지되는 키-값 저장소.',cat,2)
add('IndexedDB','IndexedDB','브라우저에서 많은 구조화 데이터를 비동기로 저장하는 로컬 데이터베이스.',cat,3)
add('웹소켓','WebSocket','클라이언트와 서버가 연결을 유지하며 양방향으로 실시간 통신하는 프로토콜.',cat,2,True)
add('서버 전송 이벤트','Server-Sent Events','서버가 하나의 연결을 통해 클라이언트로 이벤트를 계속 보내는 방식.',cat,3,['SSE'])
add('웹훅','webhook','특정 사건이 발생했을 때 다른 서버의 URL을 자동 호출하는 알림 방식.',cat,2,True)
add('브라우저 개발자 도구','browser developer tools','웹 요소·네트워크·로그·성능을 검사하는 브라우저 내장 도구.',cat,1,True)
add('네트워크 탭','Network panel','브라우저가 주고받은 요청·응답·시간을 확인하는 개발자 도구 화면.',cat,2)
add('소스맵','source map','압축·변환된 배포 코드 오류를 원본 소스 위치로 연결하는 파일.',cat,3)
add('핫 모듈 교체','hot module replacement','개발 중 전체 새로고침 없이 바뀐 모듈만 즉시 반영하는 기능.',cat,3,['HMR'])

# 6) 백엔드·API
cat='백엔드·API'
add('HTTP 메서드','HTTP method','요청이 자원에 수행할 동작을 나타내는 GET·POST 같은 값.',cat,1,True)
add('GET','GET','서버에서 자원이나 목록을 조회할 때 사용하는 HTTP 메서드.',cat,1)
add('POST','POST','새 자원을 만들거나 처리를 요청할 때 주로 사용하는 HTTP 메서드.',cat,1)
add('PUT','PUT','자원 전체를 새 내용으로 교체할 때 주로 사용하는 HTTP 메서드.',cat,2)
add('PATCH','PATCH','자원의 일부 필드만 수정할 때 주로 사용하는 HTTP 메서드.',cat,2)
add('DELETE 메서드','DELETE','서버 자원을 삭제하도록 요청하는 HTTP 메서드.',cat,1)
add('HTTP 상태 코드','HTTP status code','서버가 요청 처리 결과를 세 자리 숫자로 알려주는 값.',cat,1,True)
add('200 OK','200 OK','요청이 성공했고 응답 본문이 있음을 나타내는 상태 코드.',cat,1)
add('201 Created','201 Created','요청으로 새 자원이 성공적으로 생성되었음을 나타내는 상태 코드.',cat,2)
add('204 No Content','204 No Content','요청은 성공했지만 돌려줄 본문이 없음을 나타내는 상태 코드.',cat,2)
add('400 Bad Request','400 Bad Request','요청 형식이나 값이 잘못되어 처리할 수 없음을 나타내는 상태 코드.',cat,1)
add('401 Unauthorized','401 Unauthorized','유효한 인증 정보가 없어 요청을 처리하지 못함을 나타내는 상태 코드.',cat,2)
add('403 Forbidden','403 Forbidden','신원은 확인했지만 해당 작업 권한이 없음을 나타내는 상태 코드.',cat,2)
add('404 Not Found','404 Not Found','요청한 자원이나 경로를 찾지 못했음을 나타내는 상태 코드.',cat,1)
add('409 Conflict','409 Conflict','현재 자원 상태와 요청이 충돌함을 나타내는 상태 코드.',cat,3)
add('422 Unprocessable Content','422 Unprocessable Content','요청 문법은 맞지만 값 검증에 실패했음을 나타내는 상태 코드.',cat,3)
add('429 Too Many Requests','429 Too Many Requests','짧은 시간에 너무 많은 요청을 보내 제한되었음을 나타내는 상태 코드.',cat,2)
add('500 Internal Server Error','500 Internal Server Error','서버 내부의 예상하지 못한 오류로 요청이 실패했음을 나타내는 상태 코드.',cat,1)
add('502 Bad Gateway','502 Bad Gateway','게이트웨이가 뒤쪽 서버에서 유효한 응답을 받지 못했음을 나타내는 상태 코드.',cat,3)
add('503 Service Unavailable','503 Service Unavailable','서버가 과부하나 점검 때문에 일시적으로 요청을 처리할 수 없는 상태 코드.',cat,2)
add('요청 헤더','request header','인증·콘텐츠 형식·언어 같은 요청 부가 정보를 담는 영역.',cat,2)
add('응답 헤더','response header','캐시·콘텐츠 형식·쿠키 같은 응답 부가 정보를 담는 영역.',cat,2)
add('요청 본문','request body','POST나 PATCH 요청에서 서버로 보낼 실제 데이터를 담는 부분.',cat,1)
add('쿼리 파라미터','query parameter','URL 물음표 뒤에 붙여 필터·검색·페이지 정보를 전달하는 값.',cat,1,True)
add('경로 파라미터','path parameter','URL 경로 안에 포함해 특정 자원 식별자를 전달하는 값.',cat,1)
add('콘텐츠 타입','Content-Type','요청이나 응답 본문의 데이터 형식을 알려주는 HTTP 헤더.',cat,2)
add('Bearer 토큰','Bearer token','Authorization 헤더에 실어 API 접근 권한을 증명하는 토큰 형식.',cat,2)
add('API 키','API key','API 사용자를 식별하고 호출 권한이나 사용량을 관리하는 비밀 값.',cat,2,True)
add('액세스 토큰','access token','인증 후 일정 시간 동안 보호된 자원 접근을 허용하는 문자열.',cat,2)
add('리프레시 토큰','refresh token','만료된 액세스 토큰을 새로 발급받는 데 사용하는 장기 토큰.',cat,3)
add('JWT','JSON Web Token','서명된 JSON 정보로 사용자나 권한을 전달하는 토큰 형식.',cat,2)
add('OAuth 2.0','OAuth 2.0','비밀번호를 직접 공유하지 않고 다른 서비스 접근 권한을 위임하는 표준.',cat,3)
add('OpenID Connect','OpenID Connect','OAuth 2.0 위에서 사용자 로그인과 신원 정보를 표준화한 규격.',cat,3,['OIDC'])
add('API 버전','API version','호환되지 않는 API 변경을 구분하기 위해 붙이는 버전.',cat,2)
add('페이지네이션','pagination','많은 목록을 여러 페이지나 묶음으로 나누어 가져오는 방식.',cat,2,True)
add('커서 페이지네이션','cursor pagination','마지막 항목의 위치 토큰을 이용해 다음 목록을 가져오는 방식.',cat,3)
add('오프셋 페이지네이션','offset pagination','건너뛸 개수와 가져올 개수로 목록 범위를 지정하는 방식.',cat,3)
add('요청 제한','rate limiting','일정 시간 동안 허용할 API 요청 수를 제한하는 기능.',cat,2,True)
add('스로틀링','throttling','호출 빈도를 일정 수준 이하로 강제로 낮추는 제어.',cat,3)
add('디바운싱','debouncing','연속 입력이 멈춘 뒤 한 번만 함수를 실행하는 처리.',cat,2)
add('API 게이트웨이','API gateway','여러 백엔드 API 앞에서 인증·라우팅·제한을 한곳에서 처리하는 서버.',cat,3)
add('리버스 프록시','reverse proxy','클라이언트 요청을 대신 받아 내부 서버로 전달하는 서버.',cat,2)
add('로드 밸런서','load balancer','여러 서버에 요청을 분산해 성능과 가용성을 높이는 장치.',cat,2)
add('헬스 체크','health check','서버나 의존 서비스가 정상인지 주기적으로 확인하는 요청.',cat,2)
add('마이크로서비스','microservices','큰 시스템을 독립 배포 가능한 작은 서비스들로 나누는 구조.',cat,3)
add('모놀리식 아키텍처','monolithic architecture','대부분의 기능을 하나의 애플리케이션으로 함께 개발·배포하는 구조.',cat,2)
add('서버리스','serverless','서버 관리 대신 실행량에 따라 코드를 실행하는 클라우드 운영 방식.',cat,2)
add('엣지 함수','edge function','사용자와 가까운 네트워크 위치에서 실행되는 짧은 서버 함수.',cat,3)
add('백그라운드 잡','background job','사용자 응답과 분리해 뒤에서 실행하는 긴 작업.',cat,2)
add('작업 큐','job queue','처리할 작업을 순서대로 저장하고 워커가 가져가도록 하는 구조.',cat,2)
add('워커','worker','큐에서 작업을 꺼내 실제 처리를 수행하는 프로세스.',cat,2)
add('메시지 브로커','message broker','서비스 사이의 메시지를 저장·전달해 느슨하게 연결하는 시스템.',cat,3)
add('이벤트 기반 아키텍처','event-driven architecture','사건이 발생하면 메시지를 발행하고 구독자가 반응하도록 구성한 구조.',cat,3)
add('GraphQL','GraphQL','클라이언트가 필요한 필드만 지정해 요청하는 API 질의 언어와 런타임.',cat,3)
add('gRPC','gRPC','프로토콜 버퍼를 사용해 서비스 간 고성능 원격 호출을 제공하는 프레임워크.',cat,4)
add('OpenAPI','OpenAPI Specification','REST API 경로·입력·응답을 기계가 읽을 수 있게 문서화하는 규격.',cat,2,True)
add('Swagger UI','Swagger UI','OpenAPI 문서를 브라우저에서 읽고 직접 호출해 볼 수 있게 보여주는 도구.',cat,2)

# 7) 데이터베이스·데이터
cat='데이터베이스·데이터'
add('MySQL','MySQL','웹 서비스에서 널리 쓰이는 오픈소스 관계형 데이터베이스.',cat,2)
add('MariaDB','MariaDB','MySQL과 높은 호환성을 가진 오픈소스 관계형 데이터베이스.',cat,2)
add('Firebase Realtime Database','Realtime Database','하나의 JSON 트리 구조로 데이터를 저장하고 실시간 동기화하는 Firebase DB.',cat,2)
add('벡터 데이터베이스','vector database','임베딩을 저장하고 유사도 검색에 최적화된 데이터베이스.',cat,2,True)
add('데이터 모델','data model','서비스에서 어떤 데이터를 어떤 관계와 규칙으로 저장할지 정한 구조.',cat,2)
add('엔터티','entity','데이터 모델에서 사용자·상품처럼 독립적으로 식별되는 대상.',cat,2)
add('속성 컬럼','attribute','엔터티의 이름·가격처럼 하나의 특성을 나타내는 데이터 항목.',cat,2)
add('복합키','composite key','둘 이상의 컬럼을 함께 사용해 레코드를 유일하게 구분하는 키.',cat,3)
add('유니크 제약','unique constraint','특정 컬럼 값이 테이블 안에서 중복되지 않게 막는 규칙.',cat,2)
add('NOT NULL','NOT NULL','컬럼에 값 없음이 저장되지 않도록 강제하는 제약.',cat,2)
add('기본값','default value','새 레코드에서 값을 생략했을 때 자동으로 들어가는 값.',cat,1)
add('체크 제약','check constraint','컬럼 값이 지정한 조건을 만족할 때만 저장되게 하는 규칙.',cat,3)
add('참조 무결성','referential integrity','외래키가 실제로 존재하는 부모 레코드만 가리키도록 유지하는 성질.',cat,3)
add('일대일 관계','one-to-one relationship','한 레코드가 다른 테이블의 최대 한 레코드와 연결되는 관계.',cat,2)
add('일대다 관계','one-to-many relationship','한 부모 레코드가 여러 자식 레코드와 연결되는 관계.',cat,2)
add('다대다 관계','many-to-many relationship','양쪽 레코드가 서로 여러 개씩 연결될 수 있는 관계.',cat,2)
add('조인 테이블','junction table','다대다 관계를 두 개의 일대다 관계로 저장하는 연결 테이블.',cat,3)
add('INNER JOIN','INNER JOIN','두 테이블에서 연결 조건이 맞는 행만 반환하는 조인.',cat,2)
add('LEFT JOIN','LEFT JOIN','왼쪽 테이블의 모든 행과 일치하는 오른쪽 행을 반환하는 조인.',cat,2)
add('GROUP BY','GROUP BY','같은 값을 가진 행을 묶어 집계할 때 사용하는 SQL 구문.',cat,2)
add('HAVING','HAVING','GROUP BY로 묶은 집계 결과에 조건을 적용하는 SQL 구문.',cat,3)
add('집계 함수','aggregate function','COUNT·SUM·AVG처럼 여러 행을 하나의 값으로 계산하는 함수.',cat,2)
add('서브쿼리','subquery','다른 SQL 문 안에 포함된 조회 문.',cat,3)
add('공통 테이블 표현식','common table expression','복잡한 쿼리의 중간 결과에 이름을 붙여 재사용하는 SQL 구문.',cat,3,['CTE'])
add('뷰 테이블','database view','쿼리 결과를 가상 테이블처럼 저장해 사용하는 객체.',cat,3)
add('구체화 뷰','materialized view','쿼리 결과를 실제로 저장하고 주기적으로 갱신하는 데이터베이스 객체.',cat,4)
add('쿼리 실행 계획','query execution plan','데이터베이스가 쿼리를 어떤 순서와 방법으로 처리할지 보여주는 계획.',cat,3)
add('풀 테이블 스캔','full table scan','인덱스를 쓰지 않고 테이블의 모든 행을 읽는 조회 방식.',cat,3)
add('복합 인덱스','composite index','둘 이상의 컬럼을 순서대로 포함한 인덱스.',cat,3)
add('낙관적 잠금','optimistic locking','충돌이 드물다고 보고 저장 시점에 버전을 검사하는 동시성 제어.',cat,4)
add('비관적 잠금','pessimistic locking','충돌을 막기 위해 데이터를 읽거나 수정하는 동안 잠그는 방식.',cat,4)
add('데드락','database deadlock','여러 트랜잭션이 서로 가진 잠금을 기다리며 진행하지 못하는 상태.',cat,4)
add('격리 수준','isolation level','동시에 실행되는 트랜잭션이 서로의 변경을 볼 수 있는 정도.',cat,4)
add('원자성','atomicity','트랜잭션의 작업이 모두 성공하거나 모두 취소되어야 하는 성질.',cat,3)
add('일관성','consistency','트랜잭션 전후 데이터가 정의된 규칙을 계속 만족하는 성질.',cat,3)
add('고립성','isolation','동시 트랜잭션이 서로 간섭하지 않는 것처럼 처리되는 성질.',cat,3)
add('지속성','durability','커밋된 데이터가 장애가 나도 보존되어야 하는 성질.',cat,3)
add('읽기 복제본','read replica','읽기 요청을 분산하려고 원본 DB 데이터를 복제한 서버.',cat,3)
add('수평 분할','horizontal partitioning','행을 기준으로 데이터를 여러 파티션에 나누는 방식.',cat,3)
add('수직 분할','vertical partitioning','컬럼이나 기능을 기준으로 데이터를 나누는 방식.',cat,3)
add('데이터 웨어하우스','data warehouse','분석과 보고를 위해 여러 시스템의 데이터를 통합해 저장한 곳.',cat,3)
add('ETL','Extract Transform Load','데이터를 추출하고 변환한 뒤 목적 저장소에 적재하는 과정.',cat,3)
add('ELT','Extract Load Transform','데이터를 먼저 저장소에 넣고 그 안에서 변환하는 과정.',cat,3)
add('데이터 파이프라인','data pipeline','데이터 수집·변환·저장·전달 단계를 자동으로 연결한 흐름.',cat,2)
add('시드 데이터','seed data','개발·테스트 시작 시 데이터베이스에 미리 넣는 기본 데이터.',cat,2,True)
add('픽스처','fixture','테스트를 반복 가능하게 만들기 위해 준비해 둔 입력 데이터와 환경.',cat,2)

# 8) Git·DevOps·클라우드
cat='Git·DevOps·클라우드'
add('풀','pull','원격 저장소의 변경을 받아 현재 브랜치에 통합하는 Git 작업.',cat,1)
add('페치','fetch','원격 저장소 변경 이력만 받아오고 현재 브랜치에는 합치지 않는 작업.',cat,2)
add('체크아웃','checkout','특정 브랜치나 커밋 상태로 작업 폴더를 전환하는 Git 작업.',cat,2)
add('스위치 명령','git switch','작업할 Git 브랜치를 전환하는 명령.',cat,2)
add('리베이스','rebase','브랜치의 시작점을 다른 커밋 위로 옮겨 이력을 다시 만드는 작업.',cat,3)
add('체리픽','cherry-pick','다른 브랜치의 특정 커밋 하나만 현재 브랜치에 적용하는 작업.',cat,3)
add('스태시','stash','커밋하지 않은 변경을 임시 보관하고 작업 폴더를 깨끗하게 만드는 기능.',cat,2)
add('태그','Git tag','특정 커밋에 버전명 같은 고정 이름을 붙이는 Git 객체.',cat,2)
add('머지 충돌','merge conflict','같은 코드 부분의 서로 다른 변경을 Git이 자동으로 합치지 못한 상태.',cat,2,True)
add('원격 저장소','remote repository','인터넷이나 서버에 있어 여러 사람이 공유하는 Git 저장소.',cat,1)
add('origin','origin','클론할 때 기본 원격 저장소에 관례적으로 붙는 이름.',cat,2)
add('HEAD','Git HEAD','현재 체크아웃한 브랜치의 최신 커밋을 가리키는 포인터.',cat,3)
add('커밋 해시','commit hash','각 Git 커밋을 유일하게 식별하는 문자열.',cat,2)
add('커밋 메시지','commit message','변경 목적과 내용을 설명하는 커밋 기록 문구.',cat,1,True)
add('세맨틱 버저닝','semantic versioning','호환성 변화에 따라 주·부·패치 번호를 올리는 버전 규칙.',cat,2,['SemVer'])
add('체인지로그','changelog','버전별 새 기능·변경·수정 사항을 기록한 문서.',cat,2)
add('모노레포','monorepo','여러 앱이나 패키지 코드를 하나의 저장소에서 관리하는 방식.',cat,3)
add('워크스페이스','workspace','여러 패키지나 프로젝트를 함께 개발하도록 묶은 작업 영역.',cat,2)
add('락 파일','lockfile','설치된 의존성의 정확한 버전과 무결성 정보를 고정한 파일.',cat,2,True)
add('시맨틱 릴리스','semantic release','커밋 규칙을 읽어 버전과 변경 로그·배포를 자동화하는 방식.',cat,3)
add('CI','continuous integration','코드 변경마다 자동 빌드와 테스트를 실행해 통합 문제를 빨리 찾는 방식.',cat,2,True)
add('CD','continuous delivery','검증된 변경을 언제든 배포할 수 있게 자동화하는 방식.',cat,2,True)
add('파이프라인','CI pipeline','빌드·테스트·배포 단계를 순서대로 실행하는 자동화 흐름.',cat,2)
add('워크플로','workflow','특정 이벤트에 따라 실행되는 자동화 작업과 단계의 정의.',cat,2)
add('러너','CI runner','CI 작업 명령을 실제로 실행하는 서버나 가상 환경.',cat,2)
add('빌드 아티팩트','build artifact','빌드 결과로 생성된 앱 파일·패키지·보고서.',cat,2)
add('배포 환경','deployment environment','개발·테스트·스테이징·운영처럼 목적이 다른 실행 환경.',cat,2)
add('스테이징','staging','운영 배포 전 실제와 비슷한 조건에서 최종 검증하는 환경.',cat,2,True)
add('프로덕션','production','실제 사용자가 이용하는 운영 환경.',cat,1,True)
add('개발 환경','development environment','개발자가 코드를 수정하고 빠르게 시험하는 환경.',cat,1)
add('설정 파일','configuration file','프로그램 동작 옵션과 환경별 값을 저장한 파일.',cat,1)
add('시크릿','secret','API 키·비밀번호처럼 공개 저장소에 넣으면 안 되는 민감한 설정 값.',cat,1,True)
add('.env 파일','.env file','환경 변수를 키-값 형태로 적는 파일로 보통 버전 관리에서 제외합니다.',cat,2,True)
add('컨테이너','container','앱과 필요한 실행 환경을 격리해 어디서나 비슷하게 실행하는 단위.',cat,2,True)
add('컨테이너 이미지','container image','컨테이너 실행에 필요한 파일과 설정을 담은 읽기 전용 템플릿.',cat,2)
add('Docker','Docker','컨테이너 이미지를 만들고 실행·배포하는 대표 플랫폼.',cat,2)
add('Dockerfile','Dockerfile','컨테이너 이미지를 만드는 단계와 명령을 적은 파일.',cat,2)
add('Docker Compose','Docker Compose','여러 컨테이너 서비스와 네트워크·볼륨을 한 파일로 실행하는 도구.',cat,2)
add('이미지 레지스트리','container registry','컨테이너 이미지를 저장하고 내려받는 서버.',cat,2)
add('볼륨','container volume','컨테이너가 삭제되어도 데이터를 유지하도록 연결한 저장 공간.',cat,2)
add('Kubernetes','Kubernetes','많은 컨테이너의 배포·확장·복구를 자동화하는 오케스트레이션 플랫폼.',cat,3)
add('파드','Kubernetes Pod','Kubernetes에서 함께 실행되는 하나 이상의 컨테이너 묶음.',cat,3)
add('디플로이먼트','Kubernetes Deployment','파드의 원하는 개수와 업데이트 방식을 관리하는 Kubernetes 객체.',cat,3)
add('서비스 객체','Kubernetes Service','변하는 파드 주소 앞에 안정적인 네트워크 접근점을 제공하는 객체.',cat,3)
add('인그레스','Kubernetes Ingress','클러스터 외부 HTTP 요청을 내부 서비스로 라우팅하는 규칙.',cat,4)
add('오토스케일링','autoscaling','부하에 따라 서버나 파드 수를 자동으로 늘리고 줄이는 기능.',cat,3)
add('클라우드','cloud computing','인터넷을 통해 서버·저장소·데이터베이스 같은 컴퓨팅 자원을 빌려 쓰는 방식.',cat,1)
add('가상 머신','virtual machine','물리 서버 자원을 나눠 독립된 컴퓨터처럼 실행하는 가상 환경.',cat,2)
add('리전','cloud region','클라우드 데이터센터가 위치한 지리적 운영 구역.',cat,2)
add('가용 영역','availability zone','한 리전 안에서 전력과 네트워크 장애를 분리한 데이터센터 구역.',cat,3)
add('CDN','content delivery network','여러 지역의 캐시 서버에서 정적 파일을 가까이 전달하는 네트워크.',cat,2)
add('DNS','Domain Name System','도메인 이름을 서버 IP 주소로 바꾸는 인터넷 이름 시스템.',cat,2,True)
add('도메인','domain name','사람이 기억하기 쉬운 인터넷 서비스 주소 이름.',cat,1)
add('TLS','Transport Layer Security','인터넷 통신을 암호화하고 서버 신원을 확인하는 보안 프로토콜.',cat,2)
add('SSL 인증서','TLS certificate','도메인과 공개키의 소유 관계를 인증 기관이 서명한 전자 문서.',cat,2)
add('SSH','Secure Shell','원격 서버에 암호화된 명령줄 연결을 제공하는 프로토콜.',cat,2,True)
add('크론','cron','정해진 시간이나 주기에 명령을 자동 실행하는 스케줄러.',cat,2)
add('관측 가능성','observability','로그·메트릭·트레이스로 시스템 내부 상태를 추론할 수 있는 능력.',cat,3,True)
add('메트릭','metric','시간에 따라 수치로 측정되는 시스템 상태나 성능 데이터.',cat,2)
add('분산 추적','distributed tracing','여러 서비스에 걸친 하나의 요청 흐름과 시간을 연결해 보는 기술.',cat,3)
add('로그 집계','log aggregation','여러 서버와 앱의 로그를 한곳에 모아 검색·분석하는 처리.',cat,3)
add('업타임','uptime','서비스가 정상적으로 사용 가능했던 시간이나 비율.',cat,2)
add('SLA','service-level agreement','서비스 제공자와 고객이 합의한 가용성·응답시간 등의 보장 수준.',cat,3)
add('SLO','service-level objective','팀이 달성하려고 정한 신뢰성 지표의 목표값.',cat,3)
add('SLI','service-level indicator','가용성·지연시간처럼 서비스 수준을 실제로 측정하는 지표.',cat,3)
add('처리량','throughput','시스템이 일정 시간에 처리하는 요청이나 데이터 양.',cat,2)

# 9) 테스트·품질·보안
cat='테스트·품질·보안'
add('테스트 케이스','test case','입력·실행 절차·기대 결과를 정리한 하나의 검증 항목.',cat,1,True)
add('테스트 시나리오','test scenario','사용자 흐름 전체를 기준으로 여러 테스트 케이스를 묶은 상황.',cat,2)
add('테스트 계획','test plan','범위·환경·담당·일정·종료 조건을 정리한 테스트 문서.',cat,2)
add('회귀 테스트','regression test','변경 후 기존 기능이 다시 깨지지 않았는지 확인하는 테스트.',cat,2,True)
add('스모크 테스트','smoke test','빌드의 핵심 기능이 최소한 실행되는지 빠르게 확인하는 테스트.',cat,2)
add('엔드투엔드 테스트','end-to-end test','실제 사용자 흐름처럼 프론트부터 DB까지 전체를 검증하는 테스트.',cat,2,['E2E'])
add('UI 테스트','UI test','버튼·입력·화면 전환 같은 사용자 인터페이스 동작을 자동 검증하는 테스트.',cat,2)
add('스냅샷 테스트','snapshot test','렌더링 결과나 직렬화 결과를 이전 저장본과 비교하는 테스트.',cat,3)
add('골든 테스트','golden test','UI 이미지 결과를 기준 이미지와 픽셀 단위로 비교하는 테스트.',cat,3)
add('계약 테스트','contract test','서비스 사이 요청·응답 규격이 서로 호환되는지 검증하는 테스트.',cat,3)
add('성능 테스트','performance test','응답 시간·처리량·자원 사용량이 기준을 만족하는지 측정하는 테스트.',cat,2)
add('부하 테스트','load test','예상 사용자 수나 요청량에서 시스템 성능을 측정하는 테스트.',cat,2)
add('스트레스 테스트','stress test','한계를 넘는 부하를 가해 장애 지점과 복구 능력을 확인하는 테스트.',cat,3)
add('사용성 테스트','usability test','실제 사용자가 과업을 얼마나 쉽고 정확하게 수행하는지 관찰하는 테스트.',cat,2,True)
add('탐색적 테스트','exploratory testing','정해진 절차에만 의존하지 않고 사용하며 결함을 발견하는 테스트.',cat,2)
add('테스트 더블','test double','실제 의존성을 대신해 테스트에서 사용하는 대체 객체의 통칭.',cat,3)
add('목 객체','mock object','호출 여부와 인자를 검증할 수 있도록 만든 가짜 의존 객체.',cat,2)
add('스텁','stub','정해진 입력에 미리 준비한 결과를 반환하는 단순 대체 객체.',cat,2)
add('페이크','fake','실제보다 단순하지만 동작 가능한 구현을 가진 테스트용 대체 객체.',cat,3)
add('코드 커버리지','code coverage','테스트가 실행한 코드 줄·분기·함수의 비율.',cat,2)
add('분기 커버리지','branch coverage','조건문의 참과 거짓 경로가 테스트된 비율.',cat,3)
add('테스트 피라미드','test pyramid','많은 단위 테스트와 적은 수의 통합·E2E 테스트를 권하는 구성 원칙.',cat,3)
add('정적 분석','static analysis','프로그램을 실행하지 않고 코드에서 오류와 위험 패턴을 찾는 검사.',cat,2,True)
add('포매터','code formatter','코드 들여쓰기와 줄바꿈을 정해진 스타일로 자동 정리하는 도구.',cat,1)
add('타입 체커','type checker','자료형 규칙 위반을 실행 전에 찾아주는 도구.',cat,2)
add('취약점','vulnerability','공격자가 시스템 보안을 해칠 수 있는 설계나 구현의 약점.',cat,2,True)
add('위협 모델링','threat modeling','보호할 자산·공격자·공격 경로·대응책을 체계적으로 분석하는 과정.',cat,3)
add('공격 표면','attack surface','외부 입력과 접근점 가운데 공격에 이용될 수 있는 전체 범위.',cat,3)
add('입력 검증','input validation','외부 입력의 형식·길이·범위를 확인해 잘못된 데이터를 거부하는 처리.',cat,1,True)
add('출력 인코딩','output encoding','사용자 데이터를 HTML 등 문맥에 맞게 변환해 코드 실행을 막는 처리.',cat,3)
add('SQL 인젝션','SQL injection','입력값으로 악성 SQL을 삽입해 DB 명령을 바꾸는 공격.',cat,2,True)
add('XSS','cross-site scripting','웹페이지에 악성 스크립트를 삽입해 다른 사용자의 브라우저에서 실행하는 공격.',cat,2)
add('CSRF','cross-site request forgery','로그인된 사용자의 권한으로 원치 않는 요청을 보내게 만드는 공격.',cat,3)
add('경로 순회','path traversal','파일 경로 조작으로 허용되지 않은 파일에 접근하는 공격.',cat,3)
add('명령어 인젝션','command injection','사용자 입력을 통해 서버 운영체제 명령을 실행시키는 공격.',cat,3)
add('비밀정보 노출','secret exposure','API 키·토큰·비밀번호가 코드나 로그에 공개되는 보안 사고.',cat,2,True)
add('암호화','encryption','키를 가진 사람만 읽을 수 있도록 데이터를 변환하는 기술.',cat,2)
add('단방향 해시','one-way hash','원본 복원이 어렵게 데이터를 고정 길이 값으로 변환하는 방식.',cat,2)
add('비밀번호 솔트','password salt','같은 비밀번호도 다른 해시가 나오게 추가하는 무작위 값.',cat,3)
add('다중 요소 인증','multi-factor authentication','비밀번호 외에 기기·생체 등 다른 확인 요소를 함께 요구하는 인증.',cat,2,['MFA'])
add('권한 역할','role-based access control','사용자 역할에 따라 접근 권한을 묶어 부여하는 방식.',cat,3,['RBAC'])
add('감사 로그','audit log','누가 언제 어떤 중요 작업을 했는지 변경 불가능하게 남기는 기록.',cat,2)
add('개인 식별 정보','personally identifiable information','개인을 직접 또는 간접적으로 식별할 수 있는 정보.',cat,2,['PII'])
add('데이터 최소화','data minimization','서비스 목적에 필요한 최소한의 개인정보만 수집하는 원칙.',cat,2)
add('보안 헤더','security header','브라우저의 보안 동작을 강화하도록 서버가 보내는 HTTP 헤더.',cat,3)
add('콘텐츠 보안 정책','Content Security Policy','허용된 스크립트·이미지 출처를 제한해 XSS 위험을 줄이는 정책.',cat,3,['CSP'])
add('의존성 취약점 검사','dependency scanning','사용 중인 라이브러리 버전에 알려진 보안 문제가 있는지 검사하는 작업.',cat,2)
add('SBOM','software bill of materials','소프트웨어에 포함된 라이브러리와 버전 목록을 기록한 명세.',cat,3)
add('오류 추적','error tracking','배포 앱에서 발생한 예외와 크래시 정보를 수집·분류하는 기능.',cat,2,True)
add('크래시 리포트','crash report','앱 종료 시점의 오류·기기·스택 정보를 담은 보고서.',cat,2)
add('재현 단계','steps to reproduce','같은 버그를 다시 발생시키기 위한 구체적인 행동 순서.',cat,1,True)
add('심각도','severity','버그가 사용자와 시스템에 미치는 영향의 크기.',cat,2)
add('우선순위','priority','버그나 작업을 얼마나 빨리 처리할지 정한 순서.',cat,1)
add('근본 원인 분석','root cause analysis','표면 증상보다 실제로 문제를 일으킨 원인을 찾는 과정.',cat,2,['RCA'])
add('포스트모템','postmortem','장애 후 원인·영향·대응·재발 방지책을 비난 없이 정리한 문서.',cat,3)

# 10) 모바일·앱 출시
cat='모바일·앱 출시'
add('앱 패키지 이름','application ID','안드로이드에서 앱을 전 세계적으로 유일하게 식별하는 문자열.',cat,2,True)
add('번들 식별자','bundle identifier','애플 플랫폼에서 앱을 유일하게 식별하는 문자열.',cat,2)
add('버전 이름','version name','사용자에게 보이는 1.2.0 같은 앱 버전 문자열.',cat,1)
add('서명 키','signing key','앱 배포 파일에 전자 서명을 만드는 비밀 개인 키.',cat,2,True)
add('프로비저닝 프로파일','provisioning profile','iOS 앱의 서명·기기·권한 정보를 연결하는 배포 설정 파일.',cat,3)
add('디버그 빌드','debug build','로그와 디버깅 기능을 포함해 개발 중 사용하는 앱 빌드.',cat,1)
add('릴리스 빌드','release build','최적화와 서명을 적용해 사용자 배포에 사용하는 앱 빌드.',cat,1,True)
add('내부 테스트','internal testing','개발팀과 소수 테스터에게 빠르게 배포하는 스토어 테스트 단계.',cat,2)
add('오픈 테스트','open testing','참여 링크나 스토어를 통해 넓은 사용자에게 공개하는 테스트 단계.',cat,2)
add('단계적 출시','staged rollout','새 버전을 일부 사용자부터 시작해 비율을 늘리며 배포하는 방식.',cat,2,True)
add('스토어 심사','store review','앱과 메타데이터가 스토어 정책을 지키는지 확인하는 절차.',cat,1)
add('스토어 메타데이터','store metadata','앱 이름·설명·스크린샷·카테고리처럼 스토어에 표시되는 정보.',cat,2)
add('개인정보 처리방침','privacy policy','수집하는 개인정보와 이용·보관·삭제 방법을 공개한 문서.',cat,1,True)
add('콘텐츠 등급','content rating','앱 내용에 따라 적합한 사용자 연령을 분류한 등급.',cat,2)
add('권한 선언','permission declaration','앱이 카메라·위치 같은 시스템 기능을 사용한다고 등록하는 설정.',cat,2)
add('런타임 권한','runtime permission','앱 실행 중 민감 기능을 쓰기 전에 사용자에게 요청하는 권한.',cat,2,True)
add('딥 링크','deep link','특정 URL을 눌렀을 때 앱의 특정 화면으로 바로 이동시키는 연결.',cat,2)
add('유니버설 링크','universal link','웹 URL을 iOS 앱의 특정 화면과 안전하게 연결하는 방식.',cat,3)
add('앱 링크','Android App Links','검증된 웹 도메인 URL을 안드로이드 앱 화면과 연결하는 방식.',cat,3)
add('푸시 토큰','push token','푸시 서비스가 특정 앱 설치 기기를 식별하는 값.',cat,2)
add('알림 채널','notification channel','안드로이드에서 알림 종류별 중요도와 소리 설정을 묶는 단위.',cat,2)
add('백그라운드 제한','background restriction','배터리 보호를 위해 앱의 뒤쪽 실행을 제한하는 운영체제 정책.',cat,3)
add('앱 생명주기 이벤트','app lifecycle event','시작·중지·백그라운드 전환 등 앱 상태 변화 알림.',cat,2)
add('화면 회전','orientation change','세로와 가로 전환으로 화면 크기와 구성이 바뀌는 사건.',cat,2)
add('안전 영역','safe area','노치·상태바·홈 인디케이터에 가리지 않는 콘텐츠 표시 영역.',cat,2,True)
add('윈도 인셋','window insets','시스템 바와 키보드가 차지하는 화면 여백 정보.',cat,3)
add('적응형 레이아웃','adaptive layout','창 크기·자세·입력 방식에 맞춰 구조 자체를 바꾸는 화면 설계.',cat,2,True)
add('폴더블 자세','foldable posture','접힘·책 모드·테이블탑처럼 폴더블 기기의 물리적 상태.',cat,3)
add('앱 크래시율','crash-free users','크래시 없이 앱을 사용한 사용자 비율로 보는 안정성 지표.',cat,2)
add('ANR','Application Not Responding','안드로이드 메인 스레드가 오래 막혀 앱이 응답하지 않는 상태.',cat,3)
add('콜드 스타트','cold start','앱 프로세스가 없는 상태에서 처음 화면을 띄우는 시작 과정.',cat,2)
add('웜 스타트','warm start','앱 프로세스는 남아 있지만 화면을 다시 만드는 시작 과정.',cat,3)
add('핫 스타트','hot start','앱과 화면이 메모리에 남은 상태에서 즉시 돌아오는 시작 과정.',cat,3)
add('앱 크기','app size','사용자가 내려받고 설치할 때 필요한 앱 파일과 데이터 용량.',cat,1)
add('동적 기능 모듈','dynamic feature module','필요할 때만 내려받아 앱 설치 크기를 줄이는 안드로이드 기능 모듈.',cat,3)
add('인앱 업데이트','in-app update','스토어 화면을 떠나지 않고 앱 안에서 새 버전 설치를 안내하는 기능.',cat,3)
add('원격 설정','remote config','앱 업데이트 없이 서버 값으로 기능과 문구를 바꾸는 설정 기능.',cat,2,True)
add('크래시리틱스','Crashlytics','배포 앱의 크래시와 비정상 종료 정보를 수집하는 Firebase 도구.',cat,2)
add('앱 분석 이벤트','analytics event','사용자의 화면·버튼·완료 행동을 측정하려고 기록하는 사건.',cat,1,True)
add('어트리뷰션','attribution','광고·검색·추천 중 어떤 경로가 설치나 결제를 만들었는지 연결하는 측정.',cat,3)

# 11) UX·UI·제품·학습게임
cat='UX·UI·제품·학습게임'
add('정보 구조','information architecture','콘텐츠와 기능을 사용자가 찾기 쉽게 분류하고 연결한 구조.',cat,2,True)
add('시각적 위계','visual hierarchy','크기·색·간격으로 무엇을 먼저 봐야 하는지 알려주는 구성.',cat,1,True)
add('어포던스','affordance','요소의 생김새가 눌러짐·드래그됨 같은 사용 방법을 암시하는 성질.',cat,2)
add('피드백','interaction feedback','사용자의 행동이 인식되고 처리되었음을 시각·소리·진동으로 알려주는 반응.',cat,1,True)
add('마이크로인터랙션','microinteraction','좋아요·완료처럼 하나의 작은 행동을 즐겁고 명확하게 만드는 반응.',cat,2,True)
add('모션 디자인','motion design','이동·전환·속도를 이용해 상태 변화와 관계를 설명하는 디자인.',cat,2)
add('감속 모션','easing','애니메이션 속도를 자연스럽게 가속·감속시키는 시간 곡선.',cat,3)
add('모션 감소','reduced motion','어지러움과 집중 문제를 줄이도록 큰 애니메이션을 최소화하는 접근성 설정.',cat,2,True)
add('터치 타깃','touch target','사용자가 손가락으로 안정적으로 누를 수 있도록 확보한 상호작용 영역.',cat,1,True)
add('색상 대비','color contrast','글자와 배경을 구분할 수 있는 밝기 차이.',cat,1,True)
add('대비율','contrast ratio','전경과 배경 밝기 차이를 수치로 나타낸 접근성 지표.',cat,2)
add('스크린 리더','screen reader','화면 요소와 글자를 음성이나 점자로 읽어주는 보조 기술.',cat,2)
add('접근성 라벨','accessibility label','아이콘이나 컨트롤의 의미를 보조 기술에 전달하는 설명.',cat,2)
add('초점 순서','focus order','키보드나 보조 기술로 이동할 때 요소가 선택되는 순서.',cat,2)
add('동적 글자 크기','dynamic type','사용자 시스템 글자 크기 설정에 맞춰 앱 텍스트가 커지는 기능.',cat,2)
add('국제화','internationalization','여러 언어와 지역 형식을 지원할 수 있게 코드를 준비하는 작업.',cat,2,['i18n'])
add('현지화','localization','특정 언어와 지역에 맞게 번역·날짜·통화·문화 요소를 적용하는 작업.',cat,2,['l10n'])
add('오른쪽에서 왼쪽','right-to-left','아랍어처럼 화면 흐름과 글자가 오른쪽에서 왼쪽으로 진행되는 방향.',cat,3,['RTL'])
add('빈 상태','empty state','표시할 데이터가 없을 때 이유와 다음 행동을 안내하는 화면 상태.',cat,1,True)
add('오류 예방','error prevention','실수하기 어려운 선택지와 검증으로 오류가 생기기 전에 막는 설계.',cat,2)
add('실행 취소','undo','방금 한 작업을 이전 상태로 되돌릴 수 있는 기능.',cat,1,True)
add('확인 다이얼로그','confirmation dialog','삭제처럼 되돌리기 어려운 작업 전에 의도를 다시 확인하는 창.',cat,2)
add('점진적 공개 UX','progressive disclosure UX','처음에는 핵심만 보여주고 필요할 때 고급 기능을 펼치는 설계.',cat,2,True)
add('인지 부하','cognitive load','사용자가 동시에 기억하고 판단해야 하는 정보의 부담.',cat,2,True)
add('선택 피로','choice overload','선택지가 너무 많아 결정이 느려지거나 포기하게 되는 현상.',cat,2)
add('피츠의 법칙','Fitts’s law','대상이 크고 가까울수록 더 빠르고 쉽게 누를 수 있다는 법칙.',cat,3)
add('힉의 법칙','Hick’s law','선택지가 많고 복잡할수록 결정 시간이 길어진다는 법칙.',cat,3)
add('제이콥의 법칙','Jakob’s law','사용자는 다른 앱에서 익힌 방식대로 새 앱도 동작하기를 기대한다는 원칙.',cat,3)
add('온보딩 체크리스트','onboarding checklist','처음 사용자가 핵심 행동을 순서대로 완료하도록 안내하는 목록.',cat,2)
add('코치 마크','coach mark','처음 보는 기능 위에 짧게 사용법을 표시하는 안내 요소.',cat,2)
add('툴팁','tooltip','요소에 대한 짧은 설명을 일시적으로 보여주는 작은 팝업.',cat,1)
add('사용자 여정','user journey','사용자가 목표를 달성하기까지 겪는 단계·감정·접점을 정리한 흐름.',cat,2)
add('퍼널','funnel','시작부터 가입·완료·결제까지 단계별 사용자 감소를 보는 분석 구조.',cat,2,True)
add('전환율','conversion rate','특정 행동을 완료한 사용자의 비율.',cat,1)
add('활성 사용자','active user','정의된 기간에 의미 있는 행동을 한 사용자.',cat,1)
add('DAU','daily active users','하루 동안 앱에서 의미 있는 활동을 한 고유 사용자 수.',cat,2)
add('MAU','monthly active users','한 달 동안 앱에서 의미 있는 활동을 한 고유 사용자 수.',cat,2)
add('고착도','stickiness','사용자가 월간 사용 중 얼마나 자주 일간 사용으로 돌아오는지 보는 지표.',cat,3)
add('코호트','cohort','가입일이나 행동처럼 같은 특성을 가진 사용자 집단.',cat,2)
add('A/B 테스트','A/B test','두 버전을 무작위 사용자에게 보여주고 지표 차이를 비교하는 실험.',cat,2,True)
add('가설','product hypothesis','특정 변화가 사용자 행동과 지표를 개선할 것이라는 검증 가능한 예상.',cat,1)
add('북극성 지표','north star metric','제품이 사용자에게 제공하는 핵심 가치를 대표하는 장기 지표.',cat,3)
add('가드레일 지표','guardrail metric','주요 지표 개선 과정에서 악화되면 안 되는 안전 지표.',cat,3)
add('게임화','gamification','게임이 아닌 활동에 목표·보상·진행 요소를 적용하는 설계.',cat,1,True)
add('게임 기반 학습','game-based learning','학습 내용 자체를 게임 규칙과 플레이 안에 넣는 교육 방식.',cat,2,True)
add('경험치','experience points','학습 행동의 누적 진행도를 숫자로 보여주는 보상.',cat,1,['XP'])
add('레벨','player level','누적 경험치나 숙련도에 따라 올라가는 장기 진행 단계.',cat,1)
add('연속 학습','learning streak','정해진 기간 동안 학습을 이어간 연속 기록.',cat,1)
add('스트릭 보호','streak freeze','하루 학습을 놓쳐도 제한적으로 연속 기록을 유지해 주는 기능.',cat,2)
add('보석 재화','gems','학습 완료로 얻고 꾸미기나 힌트에 사용하는 게임 내 보상 재화.',cat,1)
add('수집 도감','collection book','배운 용어·배지·캐릭터를 모아 진행 상황을 시각화하는 화면.',cat,2)
add('퀘스트','quest','분명한 목표와 보상이 있는 짧은 학습 과제.',cat,1,True)
add('일일 미션','daily mission','매일 새로 제공되는 짧은 학습 목표.',cat,1)
add('보스 스테이지','boss stage','여러 유형의 문제를 연속으로 풀어 단원 숙련을 확인하는 특별 단계.',cat,2)
add('콤보','combo','연속 정답에 따라 보상과 피드백이 커지는 진행 장치.',cat,1)
add('퍼펙트 보너스','perfect bonus','한 세트를 틀리지 않고 마쳤을 때 주는 추가 보상.',cat,1)
add('보상 예측 가능성','reward predictability','학습 행동과 보상의 관계를 사용자가 이해할 수 있는 정도.',cat,3)
add('루트박스','loot box','무작위 보상을 상자 형태로 제공하는 시스템으로 유료 사용 시 주의가 필요한 구조.',cat,2)
add('숙련도','mastery','특정 용어를 정확히 기억하고 상황에 맞게 사용할 수 있는 정도.',cat,1,True)
add('숙달 학습','mastery learning','기준에 도달할 때까지 보충과 재도전을 반복한 뒤 다음 단계로 가는 방식.',cat,2,True)
add('인출 연습','retrieval practice','정답을 다시 읽기보다 기억에서 직접 꺼내 답하며 학습하는 방법.',cat,2,True)
add('간격 반복','spaced repetition','복습 간격을 점차 늘려 장기 기억을 강화하는 학습 방법.',cat,2,True)
add('교차 학습','interleaving','비슷한 주제와 문제 유형을 섞어 구별하고 적용하는 힘을 높이는 방법.',cat,3)
add('적응형 난이도','adaptive difficulty','정답률·속도·자신감에 따라 다음 문제 난이도를 조절하는 기능.',cat,2,True)
add('힌트 사다리','hint ladder','작은 단서부터 정답에 가까운 단서까지 단계적으로 제공하는 힌트 구조.',cat,2,True)
add('자신감 평가','confidence rating','답한 뒤 사용자가 얼마나 확신했는지 표시해 착각과 실제 이해를 구분하는 기능.',cat,2)
add('오답 노트','error notebook','틀리거나 헷갈린 항목과 이유를 모아 다시 복습하는 기능.',cat,1,True)
add('오개념','misconception','그럴듯하지만 잘못 이해하고 있는 개념이나 규칙.',cat,2)
add('변별 오답','diagnostic distractor','특정 오개념을 가진 사람이 고르기 쉬워 이해 상태를 알려주는 오답 선택지.',cat,3)
add('즉시 피드백','immediate feedback','답변 직후 정오와 이유를 알려 학습 오류를 바로 수정하는 방식.',cat,1,True)
add('설명 회상','explain-back','배운 개념을 자신의 말로 짧게 설명해 이해를 확인하는 학습 활동.',cat,2)
add('플로 상태','flow state','과제 난이도와 능력이 균형을 이뤄 깊게 몰입한 상태.',cat,3)
add('세션 길이','session length','한 번 앱을 열어 학습하는 데 사용한 시간.',cat,1)
add('마찰','user friction','목표 행동까지 필요 이상으로 많은 단계나 노력이 드는 문제.',cat,2)
add('재참여','re-engagement','쉬었던 사용자가 알림·미션·콘텐츠를 통해 다시 돌아오는 행동.',cat,2)

# 중복을 제거하고 기존 367개와 겹치지 않는 신규 500개를 선택한다.
def norm(s):
    if s is None: return ''
    s=unicodedata.normalize('NFKC',str(s)).lower()
    return re.sub(r'[^0-9a-z가-힣]+','',s)
existing_ko={norm(x.get('termKo')) for x in base}
existing_en={norm(x.get('termEn')) for x in base if x.get('termEn')}
unique=[]; seen_ko=set(); seen_en=set()
for x in A:
    nk,ne=norm(x['termKo']),norm(x['termEn'])
    if not nk or nk in existing_ko or nk in seen_ko: continue
    # 영문명 중복은 한국어 개념이 다른 경우도 있어 한국어 중복만 강제 제거한다.
    seen_ko.add(nk); seen_en.add(ne)
    x.update(collection='vibe-v2',source='OpenAI·Anthropic·MCP·GitHub·Android·Apple·MDN 등 공식 문서 기반 한글 재작성')
    x['slug']=re.sub(r'-+','-',re.sub(r'[^a-z0-9가-힣]+','-',(x['termEn'] or x['termKo']).lower())).strip('-')
    x['reviewStatus']='reviewed-2026-07'
    x['quizEnabled']=True
    unique.append(x)

quotas={
 '생성형 AI·모델':45,
 '프롬프트·컨텍스트·RAG':45,
 '에이전트·바이브코딩':55,
 '프로그래밍 핵심':50,
 '웹·프론트엔드':45,
 '백엔드·API':40,
 '데이터베이스·데이터':35,
 'Git·DevOps·클라우드':50,
 '테스트·품질·보안':40,
 '모바일·앱 출시':30,
 'UX·UI·제품·학습게임':65,
}
additions=[]
for category,quota in quotas.items():
    pool=[x for x in unique if x['category']==category]
    if len(pool)<quota:
        raise SystemExit(f'{category} 용어가 부족합니다: {len(pool)}/{quota}')
    additions.extend(pool[:quota])
if len(additions)!=500:
    raise SystemExit(f'신규 선택 수 오류: {len(additions)}')

# 기존 slug 충돌 방지 및 v2 필드 보강
used=set()
for i,x in enumerate(base):
    slug=x.get('slug') or re.sub(r'[^a-z0-9가-힣]+','-',(x.get('termEn') or x['termKo']).lower()).strip('-')
    orig=slug; n=2
    while slug in used:
        slug=f'{orig}-{n}'; n+=1
    used.add(slug); x['slug']=slug
    x['id']=f'base-{i+1:04d}'
for i,x in enumerate(additions):
    slug=x['slug'] or f'term-{i+1}'
    orig=slug; n=2
    while slug in used:
        slug=f'{orig}-{n}'; n+=1
    used.add(slug); x['slug']=slug
    x['id']=f'new-{i+1:04d}'

master=base+additions

(OUT/'glossary_cleaned_367.json').write_text(json.dumps(base,ensure_ascii=False,indent=2),encoding='utf-8')
(OUT/'glossary_additions_500.json').write_text(json.dumps(additions,ensure_ascii=False,indent=2),encoding='utf-8')
(OUT/'glossary_master_867.json').write_text(json.dumps(master,ensure_ascii=False,indent=2),encoding='utf-8')

fields=['id','termKo','termEn','def','collection','category','difficulty','vibeCore','slug','source','quizEnabled','reviewStatus']
with open(OUT/'glossary_master_867.csv','w',newline='',encoding='utf-8-sig') as f:
    w=csv.DictWriter(f,fieldnames=fields,extrasaction='ignore'); w.writeheader(); w.writerows(master)

# 자동 점검 보고서
from collections import Counter
report={
 'base_count':len(base),'addition_count':len(additions),'master_count':len(master),
 'base_difficulty':dict(Counter(x['difficulty'] for x in base)),
 'addition_difficulty':dict(Counter(x['difficulty'] for x in additions)),
 'master_categories':dict(Counter(x['category'] for x in master)),
 'missing_termEn':sum(not x.get('termEn') for x in master),
 'duplicate_termKo':len(master)-len({norm(x['termKo']) for x in master}),
 'duplicate_slug':len(master)-len({x['slug'] for x in master}),
 'volatile_count':sum(bool(x.get('volatile')) for x in master),
}
(OUT/'glossary_validation_report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps(report,ensure_ascii=False,indent=2))
